# Use the official Golang image as the base image
FROM golang:1.23-alpine as builder

# Set the working directory
WORKDIR /app

# Copy the Go modules files and download dependencies
COPY go.mod ./
RUN go mod download

# Copy the rest of the application code
COPY . .

# Build the Go application
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/client

# Stage 2: Create a minimal image with the compiled Go binary
FROM alpine:latest

# Install bash and jq in Alpine
RUN apk add --no-cache bash jq

# Install bash in Alpine
RUN apk add --no-cache bash

# Set the working directory inside the container
WORKDIR /app

# Copy the binary from the builder stage
COPY --from=builder /app/client /app/client

# Copy the TLS certificate and key files
COPY ./certs /app/certs
COPY ./config /app/config

# Copy the run_load.sh script and ensure it's executable
COPY run_load.sh /app/run_load.sh
RUN chmod +x /app/run_load.sh


# Start the application
CMD ["./run_load.sh"]