AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template for creating an ECR repository with
  lifecycle policy and image scanning.

Parameters:
  RepositoryName:
    Type: String
    Description: The name of the ECR repository
    Default: my-ecr-repo

  EnableImageScanning:
    Type: String
    Description: Enable automated image scanning (true or false)
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'

  LifecyclePolicy:
    Type: String
    Description: JSON-formatted lifecycle policy for the ECR repository (leave empty
      if not using lifecycle policies)
    Default: ''

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      ImageScanningConfiguration:
        scanOnPush: !Ref EnableImageScanning
      LifecyclePolicy: !If
        - IsLifecyclePolicyProvided
        - LifecyclePolicyText: !Ref LifecyclePolicy
        - !Ref AWS::NoValue

Conditions:
  IsLifecyclePolicyProvided: !Not
    - !Equals
      - !Ref LifecyclePolicy
      - ''

Outputs:
  RepositoryUri:
    Description: URI of the created ECR repository
    Value: !GetAtt ECRRepository.RepositoryUri
    Export:
      Name: !Sub ${AWS::StackName}-RepositoryUri

  RepositoryArn:
    Description: ARN of the created ECR repository
    Value: !GetAtt ECRRepository.Arn
    Export:
      Name: !Sub ${AWS::StackName}-RepositoryArn