AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for Route 53 hosted zone and DNS records
  pointing to an ALB.

Parameters:
  DomainName:
    Type: String
    Description: The domain name for which you want to create a hosted zone (e.g.,
      example.com)

  SubdomainName:
    Type: String
    Default: api
    Description: The subdomain name for the API (e.g., api.example.com)

  LoadBalancerDNSName:
    Type: String
    Description: The DNS name of the ALB to which the subdomain should point

Resources:
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref DomainName

  SubdomainRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !GetAtt HostedZone.Id
      Name: !Sub ${SubdomainName}.${DomainName}
      Type: A
      AliasTarget:
        DNSName: !Ref LoadBalancerDNSName
        HostedZoneId: !GetAtt LoadBalancerCanonicalHostedZone.HostedZoneId
        EvaluateTargetHealth: false

Outputs:
  HostedZoneId:
    Description: The Hosted Zone ID for the domain
    Value: !Ref HostedZone

  SubdomainRecord:
    Description: The DNS record for the subdomain
    Value: !Sub ${SubdomainName}.${DomainName}