AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: |
  Serverless application with OP Gateway for Authorization Server (AS) with mTLS and Fargate integration.

Parameters:

  VpcStack:
    Type: String
    Description: Name of VPC stack to build off of

  EndpointStack:
    Type: String
    Description: Name of ECS Cluster stack to build off of

  MTLSImage:
    Type: String
    Description: URI of image you would like to use

  OPImage:
    Type: String
    Description: URI of image you would like to use

  APIImage:
    Type: String
    Description: URI of image you would like to use

  MongoImage:
    Type: String

Resources:

  EcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${AWS::StackName}-Cluster

  DefaultRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - ecs.amazonaws.com
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/AmazonECS_FullAccess

  MTLSTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckProtocol: TCP 
      HealthCheckPort: traffic-port
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3
      TargetType: ip
      Port: 443
      Protocol: TCP
      VpcId:
        Fn::ImportValue: !Sub ${VpcStack}-vpc-id

  MTLSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Order: 1
          TargetGroupArn: !Ref MTLSTargetGroup
          Type: forward
      LoadBalancerArn:
        Fn::ImportValue: !Sub ${EndpointStack}-nlb-arn
      Port: 443
      Protocol: TCP
    DependsOn:
      - MTLSTargetGroup

  FargateService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref EcsCluster
      DeploymentController:
        Type: ECS
      DesiredCount: 1
      HealthCheckGracePeriodSeconds: 60
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerName: MTLSContainer
          ContainerPort: 443
          TargetGroupArn: !Ref MTLSTargetGroup
      NetworkConfiguration:
          AwsvpcConfiguration:
            SecurityGroups:
              - Fn::ImportValue: !Sub ${EndpointStack}-default-security-group
            Subnets:
              - Fn::ImportValue: !Sub ${VpcStack}-public-subnet-1-id
      TaskDefinition: !Ref TaskDefinition

  FargateServiceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 7

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: MTLSContainer
          Essential: true
          Image: !Ref MTLSImage
          LogConfiguration:
              LogDriver: awslogs
              Options:
                awslogs-group: !Ref FargateServiceLogGroup
                awslogs-stream-prefix: mtls-container 
                awslogs-region: !Ref AWS::Region
          PortMappings:
            - ContainerPort: 443
              HostPort: 443
              Protocol: tcp
          Environment:
            - Name: PORT
              Value: "443" 
        - Name: OPContainer
          Essential: true
          Image: !Ref OPImage
          LogConfiguration:
              LogDriver: awslogs
              Options:
                awslogs-group: !Ref FargateServiceLogGroup
                awslogs-stream-prefix: op-container 
                awslogs-region: !Ref AWS::Region
          PortMappings:
            - ContainerPort: 3000
              HostPort: 3000
              Protocol: tcp
        - Name: APIContainer
          Essential: true
          Image: !Ref APIImage
          LogConfiguration:
              LogDriver: awslogs
              Options:
                awslogs-group: !Ref FargateServiceLogGroup
                awslogs-stream-prefix: api-container 
                awslogs-region: !Ref AWS::Region
          PortMappings:
            - ContainerPort: 8080
              HostPort: 8080
              Protocol: tcp
          Environment:
            - Name: PORT
              Value: "8080" 
        - Name: MongoContainer
          Essential: true
          Image: !Ref MongoImage
          LogConfiguration:
              LogDriver: awslogs
              Options:
                awslogs-group: !Ref FargateServiceLogGroup
                awslogs-stream-prefix: api-container 
                awslogs-region: !Ref AWS::Region
          PortMappings:
            - ContainerPort: 27017
              HostPort: 27017
              Protocol: tcp
      Cpu: '512'
      ExecutionRoleArn: !Ref DefaultRole
      Memory: '2048'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        -  FARGATE
      TaskRoleArn: !Ref DefaultRole

Outputs:
  FargateServiceName:
    Description: A reference to the created Fargate Service
    Value: !GetAtt FargateService.Name
    Export:
      Name: !Sub ${AWS::StackName}-fargate-service-name
